### ISSUE TITLE
pub not working inside tuple structs?

### ISSUE THREAD

**Issue by marioferpa** [snowfoxsh/nestify#2]
Hi, thanks for the crate, I really like it. I'm always after ways of making my code less visually stressful and this is the perfect tool for some of my files. I have found something that I _think_ should work but it doesn't, and I am wondering if it's a bug, a limitation of the tool, or skill issue from my part. 

The problem comes when writing an enum inside nest! that contains a tuple-struct-like field, like "TravelTo" in my example. I can't seem to access the enum defined inside that enum, but I can when the field is written in the "structure format", with {}. Here's a minimal reproducible example of the issue:

main.rs

    mod nest;
    fn main() {

        let access = nest::Access::Front;
        println!("Access: {:?}", access);

        let location = nest::Locations::Work;
        println!("Location: {:?}", location);
    }
    
nest.rs

    use nestify::nest;

    nest! {
        #[derive(Debug)]*
        pub enum Actions {

            MoveTo {
                from: pub enum Access {
                    Top,
                    Front,
                }
            },

            TravelTo(
                pub enum Locations {
                    Work,
                    Shop
                }
            )
        }
    }
    
Accessing the Access enum from main works, but trying to access Locations gives the following error:

> error[E0449]: visibility qualifiers are not permitted here
>   --> src/nest.rs:15:13
>    |
> 15 |             pub enum Locations {
>    |             ^^^
>    |
>    = note: enum variants and their fields always share the visibility of the enum they are in
> 
> error[E0603]: enum `Locations` is private
>  --> src/main.rs:8:26
>   |
> 8 |     let location = nest::Locations::Work;
>   |                          ^^^^^^^^^  ---- unit variant `Work` is not publicly re-exported
>   |                          |
>   |                          private enum

If it is a skill issue I guess the _pub_ keyword should go somewhere else, but I don't see where it should be. 

Thanks in advance!

**Comment by snowfoxsh** [comment]
Hi, thx for your feedback. It is NOT a skill issue. I am actively working on fixing the publicity modifiers for enums and tuple structures. Hopefully i will have this fixed in the next few days. Currently the plan is for a tuple field, if it is marked public, to also mark the type as public.

**Comment by snowfoxsh** [comment]
Issue should be fixed per #3. This issue will be closed within 48 hours
