### ISSUE TITLE
Defaults shorthand

### ISSUE THREAD

**Issue by jpedrick** [snowfoxsh/nestify#6]
It could be very handy to have shorthand for defaults:

```
nest! {
    #[defaults]*
    #>[derive(Debug)]
    struct UserProfile {
        name: String = "Ernie",
        address: struct Address {
            street: String = "123 Sesame Street",
            city: String = "New York, NY",
        },
        preferences: struct Preferences {
            newsletter: bool = true,
        },
    }
}
```

```
let ernesto = UserProfile{ name: "Ernesto", address: Address{ street: "321 Street Sesame", ..default()}, ..default() });
```

**Comment by snowfoxsh** [comment]
I think this is a bit out of the scope of the project. The point of nestify is to make it easy to define deeply nested types, not to implement values. It is designed to stick as close to rust syntax as possible, and this would be too large a deviation from pure rust. But i still appreciate your idea!
